export const paginatorDefault =
    "FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink RowsPerPageDropdown";
export const clearNumber: number = -1;
export const pt_locale = {
    startsWith: "Começa com",
    contains: "Contém",
    notContains: "Não contém",
    endsWith: "Termina com",
    equals: "Igual a",
    notEquals: "Diferente de",
    noFilter: "Sem filtro",
    lt: "Menor que",
    lte: "Menor ou igual a",
    gt: "Maior que",
    gte: "Maior ou igual a",
    dateIs: "Data igual a",
    dateIsNot: "Data diferente de",
    dateBefore: "Data é anterior",
    dateAfter: "Data é posterior",
    custom: "Personalizado",
    clear: "Limpar",
    apply: "Aplicar",
    matchAll: "Combina com todas",
    matchAny: "Combina com alguma",
    addRule: "Adicionar regra",
    removeRule: "Remover regra",
    accept: "Sim",
    reject: "Não",
    choose: "Escolher",
    upload: "Upload",
    cancel: "Cancelar",
    dayNames: [
        "Domingo",
        "Segunda",
        "Terça-feira",
        "Quarta-feira",
        "Quinta-feira",
        "Sexta-feira",
        "Sábado",
    ],
    dayNamesShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
    dayNamesMin: ["Do", "Se", "Te", "Qa", "Qi", "Sx", "Sa"],
    monthNames: [
        "Janeiro",
        "Fevereiro",
        "Março",
        "Abril",
        "Maio",
        "Junho",
        "Julho",
        "Agosto",
        "Setembro",
        "Outubro",
        "Novembro",
        "Dezembro",
    ],
    monthNamesShort: [
        "Jan",
        "Fev",
        "Mar",
        "Abr",
        "Mai",
        "Jun",
        "Jul",
        "Ago",
        "Set",
        "Out",
        "Nov",
        "Dez",
    ],
    today: "Hoje",
    weekHeader: "Sem",
    firstDayOfWeek: 0,
    dateFormat: "dd/mm/yy",
    weak: "Fraca",
    medium: "Média",
    strong: "Forte",
    passwordPrompt: "Escreva uma senha",
    emptyFilterMessage: "Nenhum resultado encontrado",
    emptyMessage: "Nenhuma opção disponível",
};
